# Generated by Django 3.1.7 on 2021-03-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherRequests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='testinsert',
            name='col',
            field=models.CharField(max_length=10),
        ),
    ]
