# Generated by Django 3.1.7 on 2021-03-10 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherRequests', '0003_auto_20210309_2116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='TestInsert',
        ),
    ]
