# Generated by Django 3.1.7 on 2021-03-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WeatherRequests', '0004_auto_20210310_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedCities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_city', models.CharField(max_length=255)),
                ('current_temp', models.IntegerField()),
                ('current_humidity', models.IntegerField()),
                ('sky_cond', models.CharField(max_length=255)),
            ],
        ),
    ]
