# Generated by Django 3.1.7 on 2021-03-10 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherRequests', '0005_requestedcities'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedcities',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
